name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro jo"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        #working-directory: 
        #shell:
        run: echo "Hello world!!!!!!!!!!!!!!!!!!!"
        
      - name: "Segunda ação"
        run: |
          echo "O seu primeiro workflow está foi criado"
          echo "Sucesso"
          cat /etc/os-release
  segundo-job:
    name: "Instalação do ambiente NodeJS"
    runs-on: ubuntu-latest 
    steps: 
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
    
